In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
# scikit-learnのpreprocessingモジュールからImputerを利用。
# モジュールのインポート
#from sklearn.preprocessing import Imputer

In [2]:
DT_merge_3 = pd.read_csv('./data/DT_merge_3.csv', index_col=0, parse_dates=True)

In [3]:
DT_merge_3

,EURJPYOPEN,EURJPYHIGH,EURJPYLOW,EURJPYCLOSE,EURJPYVOL,EURUSDOPEN,EURUSDHIGH,EURUSDLOW,EURUSDCLOSE,EURUSDVOL,USDJPYOPEN,USDJPYHIGH,USDJPYLOW,USDJPYCLOSE,USDJPYVOL
2001-01-02 23:01:00,108.81,108.81,108.81,108.81,4.0,0.9507,0.9507,0.9507,0.9507,4.0,NaN,NaN,NaN,NaN,NaN
2001-01-02 23:02:00,108.81,108.81,108.79,108.79,4.0,0.9506,0.9506,0.9505,0.9505,4.0,NaN,NaN,NaN,NaN,NaN
2001-01-02 23:03:00,108.79,108.80,108.79,108.80,4.0,0.9505,0.9507,0.9505,0.9506,4.0,114.43,114.43,114.43,114.43,4.0
2001-01-02 23:04:00,108.80,108.81,108.80,108.81,4.0,0.9506,0.9506,0.9506,0.9506,4.0,114.44,114.44,114.44,114.44,4.0
2001-01-02 23:05:00,108.81,108.81,108.81,108.81,4.0,0.9506,0.9506,0.9506,0.9506,4.0,114.44,114.44,114.44,114.44,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31 23:55:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:56:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:57:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:58:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:59:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0

In [3]:
DT_merge_3['2015-04-19 15:30:00' : '2015-04-19 15:59:00']

,EURJPYOPEN,EURJPYHIGH,EURJPYLOW,EURJPYCLOSE,EURJPYVOL,EURUSDOPEN,EURUSDHIGH,EURUSDLOW,EURUSDCLOSE,EURUSDVOL,USDJPYOPEN,USDJPYHIGH,USDJPYLOW,USDJPYCLOSE,USDJPYVOL
2015-04-19 15:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:31:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:32:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:33:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:35:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:36:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:37:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:38:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:39:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:41:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:42:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:43:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:44:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:46:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:47:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:48:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:49:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:51:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:52:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:54:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:55:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:56:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:57:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:58:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04-19 15:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
DT_merge_2000000 = DT_merge_3.tail(2000000)

In [6]:
DT_merge_2000000

,EURJPYOPEN,EURJPYHIGH,EURJPYLOW,EURJPYCLOSE,EURJPYVOL,EURUSDOPEN,EURUSDHIGH,EURUSDLOW,EURUSDCLOSE,EURUSDVOL,USDJPYOPEN,USDJPYHIGH,USDJPYLOW,USDJPYCLOSE,USDJPYVOL
2017-03-14 02:40:00,122.33,122.33,122.33,122.33,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.80,114.80,114.80,114.80,4.0
2017-03-14 02:41:00,122.34,122.34,122.34,122.34,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:42:00,122.34,122.34,122.34,122.34,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:43:00,122.34,122.34,122.34,122.34,4.0,1.0653,1.0653,1.0653,1.0653,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:44:00,122.33,122.33,122.33,122.33,4.0,1.0653,1.0653,1.0653,1.0653,4.0,114.81,114.81,114.81,114.81,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31 23:55:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:56:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:57:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:58:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:59:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0

In [6]:
print(DT_merge_3.applymap(type))

                          EURJPYOPEN       EURJPYHIGH        EURJPYLOW  \
2001-01-02 23:01:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:02:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:03:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:04:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:05:00  <class 'float'>  <class 'float'>  <class 'float'>
...                              ...              ...              ...
2020-12-31 23:55:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:56:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:57:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:58:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:59:00  <class 'float'>  <class 'float'>  <class 'float'>

                         EURJPYCLOSE        EURJPYVOL       EURUSDOPEN  \
2001-01-02 23:01:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:02:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:03:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:04:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:05:00  <class 'float'>  <class 'float'>  <class 'float'>
...                              ...              ...              ...
2020-12-31 23:55:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:56:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:57:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:58:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:59:00  <class 'float'>  <class 'float'>  <class 'float'>

                          EURUSDHIGH        EURUSDLOW      EURUSDCLOSE  \
2001-01-02 23:01:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:02:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:03:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:04:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:05:00  <class 'float'>  <class 'float'>  <class 'float'>
...                              ...              ...              ...
2020-12-31 23:55:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:56:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:57:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:58:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:59:00  <class 'float'>  <class 'float'>  <class 'float'>

                           EURUSDVOL       USDJPYOPEN       USDJPYHIGH  \
2001-01-02 23:01:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:02:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:03:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:04:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:05:00  <class 'float'>  <class 'float'>  <class 'float'>
...                              ...              ...              ...
2020-12-31 23:55:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:56:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:57:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:58:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:59:00  <class 'float'>  <class 'float'>  <class 'float'>

                           USDJPYLOW      USDJPYCLOSE        USDJPYVOL
2001-01-02 23:01:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:02:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:03:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:04:00  <class 'float'>  <class 'float'>  <class 'float'>
2001-01-02 23:05:00  <class 'float'>  <class 'float'>  <class 'float'>
...                              ...              ...              ...
2020-12-31 23:55:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:56:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:57:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:58:00  <class 'float'>  <class 'float'>  <class 'float'>
2020-12-31 23:59:00  <class 'float'>  <class 'float'>  <class 'float'>

[10516379 rows x 15 columns]

In [7]:
DT_merge_2000000_ffill=DT_merge_2000000.fillna(method='ffill')

In [8]:
DT_merge_2000000_ffill

,EURJPYOPEN,EURJPYHIGH,EURJPYLOW,EURJPYCLOSE,EURJPYVOL,EURUSDOPEN,EURUSDHIGH,EURUSDLOW,EURUSDCLOSE,EURUSDVOL,USDJPYOPEN,USDJPYHIGH,USDJPYLOW,USDJPYCLOSE,USDJPYVOL
2017-03-14 02:40:00,122.33,122.33,122.33,122.33,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.80,114.80,114.80,114.80,4.0
2017-03-14 02:41:00,122.34,122.34,122.34,122.34,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:42:00,122.34,122.34,122.34,122.34,4.0,1.0654,1.0654,1.0654,1.0654,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:43:00,122.34,122.34,122.34,122.34,4.0,1.0653,1.0653,1.0653,1.0653,4.0,114.81,114.81,114.81,114.81,4.0
2017-03-14 02:44:00,122.33,122.33,122.33,122.33,4.0,1.0653,1.0653,1.0653,1.0653,4.0,114.81,114.81,114.81,114.81,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31 23:55:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:56:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:57:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:58:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0
2020-12-31 23:59:00,126.19,126.19,126.19,126.19,4.0,1.2215,1.2215,1.2215,1.2215,4.0,103.30,103.30,103.30,103.30,4.0

In [20]:
DT_merge_2000000_ffill_12columns=DT_merge_2000000_ffill.drop(['EURJPYVOL','EURUSDVOL','USDJPYVOL'],axis=1)

In [21]:
DT_merge_2000000_ffill_12columns

,EURJPYOPEN,EURJPYHIGH,EURJPYLOW,EURJPYCLOSE,EURUSDOPEN,EURUSDHIGH,EURUSDLOW,EURUSDCLOSE,USDJPYOPEN,USDJPYHIGH,USDJPYLOW,USDJPYCLOSE
2017-03-14 02:40:00,122.33,122.33,122.33,122.33,1.0654,1.0654,1.0654,1.0654,114.80,114.80,114.80,114.80
2017-03-14 02:41:00,122.34,122.34,122.34,122.34,1.0654,1.0654,1.0654,1.0654,114.81,114.81,114.81,114.81
2017-03-14 02:42:00,122.34,122.34,122.34,122.34,1.0654,1.0654,1.0654,1.0654,114.81,114.81,114.81,114.81
2017-03-14 02:43:00,122.34,122.34,122.34,122.34,1.0653,1.0653,1.0653,1.0653,114.81,114.81,114.81,114.81
2017-03-14 02:44:00,122.33,122.33,122.33,122.33,1.0653,1.0653,1.0653,1.0653,114.81,114.81,114.81,114.81
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-31 23:55:00,126.19,126.19,126.19,126.19,1.2215,1.2215,1.2215,1.2215,103.30,103.30,103.30,103.30
2020-12-31 23:56:00,126.19,126.19,126.19,126.19,1.2215,1.2215,1.2215,1.2215,103.30,103.30,103.30,103.30
2020-12-31 23:57:00,126.19,126.19,126.19,126.19,1.2215,1.2215,1.2215,1.2215,103.30,103.30,103.30,103.30
2020-12-31 23:58:00,126.19,126.19,126.19,126.19,1.2215,1.2215,1.2215,1.2215,103.30,103.30,103.30,103.30
2020-12-31 23:59:00,126.19,126.19,126.19,126.19,1.2215,1.2215,1.2215,1.2215,103.30,103.30,103.30,103.30

In [22]:
DT_merge_2000000_ffill_12columns.to_csv("./data/DT_merge_2000000_ffill_12columns.csv ")